apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openobserve
  namespace: openobserve
  labels:
    app: openobserve
spec:
  serviceName: openobserve
  replicas: 1
  selector:
    matchLabels:
      app: openobserve
  template:
    metadata:
      labels:
        app: openobserve
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ap-south-1a
      containers:
      - name: openobserve
        image: public.ecr.aws/zinclabs/openobserve:v0.14.4
        envFrom:
        - configMapRef:
            name: openobserve-config
        ports:
        - containerPort: 5080
          name: http
        resources:
          requests:
            cpu: "1000m"
            memory: "3Gi"
          limits:
            cpu: "3000m"
            memory: "6Gi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5080
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: openobserve-data-pvc
