apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstorm
  namespace: benchmark
  labels:
    app: logstorm
spec:
  replicas: 10
  selector:
    matchLabels:
      app: logstorm
  template:
    metadata:
      labels:
        app: logstorm
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: ap-south-1a
      containers:
      - name: logstorm
        image: 916957080239.dkr.ecr.ap-south-1.amazonaws.com/logstorm:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_RATE
          value: "2000"
        - name: LOG_DURATION
          value: "3000"
        resources:
          requests:
            cpu: "100m"
            memory: "96Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      terminationGracePeriodSeconds: 5
